### ISSUE TITLE
Fix warnings

### ISSUE THREAD

**Issue by pepcots** [CITM-UPC-GameEngines-2024-BCN/HawkEngine#3]
Every build produces tones of warnings. It makes difficult to identify new warnings or even errors.
Please, fix them (most of them are about type precission, you can just static_cast or use proper types), or disable them (as I did with YAML weird warnings about dll-exports)

**Comment by pepcots** [comment]
@Peluchomp I've assigned you this issue as you are the entry point for @CITM-UPC-GameEngines-2024-BCN/platform-team , but, please, reassign it or handover it to the person you think should be fixing it

**Comment by Peluchomp** [comment]
Already fixed most of the warnings i'll add @Marco-v-BaldanII @Jordopol and @MarcoDiModica  so they can help me with the last warnings.

**Comment by Peluchomp** [comment]
Fixed all warnings except 4 that they come from an SDL file, all the others are fixed though.
