### ISSUE TITLE
"Defining YAML_CPP_API for DLL import" message for almost every file being built

### ISSUE THREAD

**Issue by pepcots** [CITM-UPC-GameEngines-2024-BCN/HawkEngine#4]
Hello @CITM-UPC-GameEngines-2024-BCN/platform-team ! Can you get ride of this anoying message when building?
It appears for almost every file being compiled!
"Defining YAML_CPP_API for DLL import"

**Comment by Peluchomp** [comment]
Should be fixed now.

**Comment by pepcots** [comment]
well done @Peluchomp !
